# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- 3.3
- 3.4
- 3.5
- 3.6
- release
- devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

env:
  global:
  - NOT_CRAN=true
  - R_REMOTES_STANDALONE=true
